# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_images:
    uses: ./.github/workflows/build-and-push-images.yaml
    with:
      push: false
      version: "dev"

  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run markdownlint
        run: make markdownlint

  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install yamllint
        run: make install-yamllint
      - name: run yamllint
        run: yamllint . -f github

  misspell:
    runs-on: ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: run misspell
        run: make misspell

  checklinks:
    name: linkspector
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          level: info
          fail_level: any
          config_file: ".linkspector.yml"

  sanity:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: run sanitycheck.py
        run: python3 ./internal/tools/sanitycheck.py
