# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Build and Publish"

on:
  push:
    branches:
      - main

jobs:
  tag-from-commit:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
    outputs:
      image-tag: ${{ steps.commit.outputs.short }}

  build_and_push_images:
    needs: tag-from-commit
    uses: ./.github/workflows/build-and-push-images.yaml
    with:
      push: true
      version: ${{ needs.tag-from-commit.outputs.image-tag }}
    secrets: inherit
